CREATE TABLE CLIENTE(
  NR_CPF        VARCHAR2(11),
  NM_CLIENTE    VARCHAR2(100),
  DT_NASCIMENTO DATE,
  ST_ATIVO CHAR(1) DEFAULT 'S',
  CONSTRAINT PKCLIENTE PRIMARY KEY (NR_CPF)
); 

CREATE TABLE PRODUTO(
  CD_PRODUTO     NUMBER(10),
  DS_PRODUTO     VARCHAR2(100),
  VL_UNITARIO    NUMBER(15,2),
  ST_ATIVO CHAR(1) DEFAULT 'S',
  CONSTRAINT PKPRODUTO PRIMARY KEY (CD_PRODUTO)
); 

CREATE TABLE VENDA(
  CD_VENDA       NUMBER(15),
  VL_TOTAL       NUMBER(15,2),
  QT_TOTAL       NUMBER(15,2),
  NR_CPFCLIENTE  VARCHAR2(11),
  DT_VENDA       DATE,
  CONSTRAINT PKVENDA PRIMARY KEY (CD_VENDA),
  CONSTRAINT FKVENDA_CLIENTE FOREIGN KEY (NR_CPFCLIENTE) REFERENCES CLIENTE (NR_CPF)
);

CREATE TABLE ITEMVENDA(
CD_VENDA        NUMBER(15),
CD_PRODUTO      NUMBER(10),
VL_UNITPROD     NUMBER(15,2),
QT_ADQUIRIDA    NUMBER(15,2),
DT_RECORD       DATE,
CONSTRAINT PKITEMVENDA PRIMARY KEY (CD_VENDA, CD_PRODUTO),
CONSTRAINT FKITEMVENDA_PRODUTO FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO (CD_PRODUTO),
CONSTRAINT FKITEMVENDA_VENDA FOREIGN KEY (CD_VENDA) REFERENCES VENDA (CD_VENDA)
);
